openapi: 3.1.0
info:
  version: R2022-2
  title: Eyedog Wayfinding API
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  x-logo:
    url: /images/logo.png
  description:
    $ref: ./info-description.md
servers:
  - url: 'https://atobe.app'
    description: 'Production server'
  - url: 'https://stage-k8.atobe.app'
    description: 'Staging server for testing'
tags: 
  - name: Shortest Route
    description: |
      Use following endpoints to access shortest route between two locations
      in web page form or JSON format
  - name: Related Information (JSON) 
    description: |
      Use following API endpoints to fetch other related information
      for proper integration
paths:
  # '/users/{username}':
  #   $ref: 'paths/users_{username}.yaml'
  /photo-route:
    $ref: paths/photo-route.yaml
  /api/buildings/pathfinder:
    $ref: paths/pathfinder.yaml
  /api/buildings/destination-nodes:
    $ref: paths/destination-nodes.yaml
  /api/buildings/categories:
    $ref: paths/categories.yaml
  # /echo:
  #   $ref: paths/echo.yaml
  # /pathItem:
  #   $ref: paths/path-item.yaml
  # /pathItemWithExamples:
  #   $ref: paths/path-item-with-examples.yaml
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
